run:
  #modules-download-mode: readonly
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: whitelist
    packages:
      - github.com/stretchr/testify/assert
      - github.com/nikandfor/snmp/asn1
      - github.com/nikandfor/snmp
      - github.com/beorn7/perks/quantile
  misspell:
    locale: US
  lll:
    line-length: 170
  goimports:
    local-prefixes: github.com/nikandfor/snmp
  prealloc:
    simple: true
    for-loops: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - unnamedResult
      - builtinShadow
      - commentedOutCode

linters:
  enable-all: true
  disable:
    - unparam
    - nakedret
    - gochecknoinits
    - gochecknoglobals
