language: go

dist: xenial

go:
  - "1.15"
  - "1.14"
  - "1.13"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
