// Code generated by "stringer -type Type ."; DO NOT EDIT.

package asn1

import "strconv"

const (
	_Type_name_0 = "BooleanIntegerBitStringOctetStringNullObjectID"
	_Type_name_1 = "SequenceSet"
)

var (
	_Type_index_0 = [...]uint8{0, 7, 14, 23, 34, 38, 46}
	_Type_index_1 = [...]uint8{0, 8, 11}
)

func (i Type) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case 16 <= i && i <= 17:
		i -= 16
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
